# This is the configuration file for pyspelling
# The rojopolis/spellcheck-github-actions action will read this file

matrix:
  - name: markdown
    aspell:
      lang: en
    sources:
      - 'ALLOYDB.md'
    dictionary:
      wordlists:
        - dictionary.txt
      encoding: utf-8
