name: Lint JSON

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'gemini-extension.json'

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run JSON Lint
        run: jq . gemini-extension.json